In [ ]:
import torch
print(torch.__version__)

2.8.0+cu126


In [ ]:
if torch.cuda.is_available():
    print("GPU is availabel")
    print(f"Using Gpu:{torch.cuda.get_device-name(0)}")
else :
    print("GPU not availabel.Using CPU")

GPU not availabel.Using CPU


## Creating a Tensor

In [ ]:
# Using empty
torch.empty(2,3)

tensor([[ 2.7604e+20,  7.1297e+28,  7.1441e+31],
        [ 1.4013e-44, -6.7406e-17,  4.4578e-41]])

In [ ]:
#check type
a=torch.empty(2,3)
type(a)

torch.Tensor

In [ ]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
torch.rand(2,3)

tensor([[0.9476, 0.3085, 0.7016],
        [0.8802, 0.3635, 0.5260]])

In [ ]:
# use of seed
#manual seed

""" sometimes we need reproduciblity so,
 the torch.manual_seed(seed_number) produces
 same random number again and again after setting
 manual_seed
 """
torch.manual_seed(100)
torch.rand(2,3 )

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor (making custom tensor of ower own values )
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
torch.tensor([[1,2],[3,4],[5,6],[7,8]])

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [ ]:
# Other ways

#arange
print("using arange -> " ,torch.arange(0,10,2))
#  torch.arange(x,y,z) : where x to y range and jump size = z

#using linspace
print("using linspace->",torch.linspace(0,10,10))
# linearly spaced number from (x,y ) and z numbers

#using eye
print("using eye->",torch.eye(5))
#creates Identity matrix
#Identity matrix diagonal elements 1 and other elements 1


#using full
print("using full->",torch.full((3,3),5))
# torch.full(x,y,z) where "(x,y)" are matrix size and each elements should be z in the matrix

using arange ->  tensor([0, 2, 4, 6, 8])
using linspace-> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye-> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full-> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [ ]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
#creating a tensor similar to existing tensor
#suppose here we are creating the similar tensor like 'x'
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x)

### Tensor Data Type

In [ ]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.dtype  #to check datatype

torch.int64

In [ ]:
#assign data type  to the sensor
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
#changing the data type of the tensor
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


In [ ]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.7136, 0.0734, 0.9035],
        [0.4222, 0.0627, 0.7780]])

### Mathematical Operations on tensor

### 1. Scalar Operations

In [ ]:
x=torch.rand(2,2)
x

tensor([[0.1508, 0.3542],
        [0.8391, 0.7564]])

In [ ]:
#additon
x+2    #here we are adding 2 explicetly in every item of the tensro

#subtraction
x-2

#multiplication
x*3

#division
x/3

#int division
((x*100)//3)

#mod
((x*100)//3)%2

#power
x**2



tensor([[0.0227, 0.1255],
        [0.7041, 0.5721]])

### 2. Element wise operation on tensors

In [ ]:
a=torch.rand(2,3)
b=torch.rand(2,3)

In [ ]:
print(a)
print(b)

tensor([[0.2613, 0.2109, 0.6565],
        [0.7500, 0.6102, 0.8886]])
tensor([[0.5807, 0.1320, 0.6473],
        [0.5242, 0.6406, 0.0413]])


In [ ]:
#addition  (all element wise operations)
a+b

#subtraction
a-b

#multiplication
a*b

#division
a/b

#power
a**b

#mod
a%b



tensor([[0.2613, 0.0789, 0.0092],
        [0.2258, 0.6102, 0.0217]])

##### some element wise operations on the single tensor

In [ ]:
c=torch.tensor([1,-2,3,-4])
c

tensor([ 1, -2,  3, -4])

In [ ]:
 #finding absolute value
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
#Negative of the tensor elements
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d=torch.tensor([1.9,2.3,3.7,4.4])


In [ ]:
#round  (rounding off the numbers )
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
#ceil (number will roundoff to  upper value )
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
#floor (numbers will roundoff to lowers values )
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
#clamp (keeping numbers in given min and max range)
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### Reduction Operation

In [ ]:
#Reducing complete tensor into a single number
e= torch.randint(size=(2,3),low=1,high=10,dtype=torch.float32)
e

tensor([[1., 8., 8.],
        [7., 5., 9.]])

In [ ]:
#total sum of all the elements
torch.sum(e)

#sum along columns
torch.sum(e,dim=0)

#sum along rows
torch.sum(e,dim=1)

tensor([ 8, 18])

In [ ]:
#mean
torch.mean(e)

#column wise mean:
torch.mean(e,dim=0)

tensor([0.0000, 7.0000, 6.5000])

In [ ]:
#median
torch.median(e)

tensor(5.)

In [ ]:
#max and min
torch.max(e)
torch.min(e)

tensor(1.)

In [ ]:
#product of all elements
torch.prod(e)

tensor(20160.)

In [ ]:
#standard deviation
torch.std(e)

tensor(2.9439)

In [ ]:
#Variance
torch.var(e)

tensor(8.6667)

In [ ]:
#argmax  (postion of max argument )
torch.argmax(e)

tensor(5)

In [ ]:
#argmin (position of min argument)
torch.argmin(e)

tensor(0)

### 4.Matrix operations

In [ ]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)

In [ ]:
print(f)
print(g)

tensor([[2, 4, 3],
        [5, 2, 7]])
tensor([[6, 5],
        [3, 7],
        [6, 6]])


In [ ]:
#Matrix Multiplication
torch.matmul(f,g)

tensor([[42, 56],
        [78, 81]])

In [ ]:
vec1=torch.tensor([1,2])
vec2=torch.tensor([3,4])

#dot product
torch.dot(vec1,vec2)

tensor(11)

In [ ]:
#transpose
torch.transpose(f,0,1)  #here 0 and 1 what we want to transpose row with columns

tensor([[2, 5],
        [4, 2],
        [3, 7]])

In [ ]:
# Transpose of a 3d Matrix
h = torch.rand(2, 3, 4)
print("Original shape:", h.shape)

# Transpose dimension 0 (depth) and dimension 1 (height)
h_transposed_0_1 = torch.transpose(h, 0, 1)
print("Shape after transposing dimensions 0 and 1:", h_transposed_0_1.shape)

# Transpose dimension 0 (depth) and dimension 2 (width)
h_transposed_0_2 = torch.transpose(h, 0, 2)
print("Shape after transposing dimensions 0 and 2:", h_transposed_0_2.shape)

# Transpose dimension 1 (height) and dimension 2 (width)
h_transposed_1_2 = torch.transpose(h, 1, 2)
print("Shape after transposing dimensions 1 and 2:", h_transposed_1_2.shape)

Original shape: torch.Size([2, 3, 4])
Shape after transposing dimensions 0 and 1: torch.Size([3, 2, 4])
Shape after transposing dimensions 0 and 2: torch.Size([4, 3, 2])
Shape after transposing dimensions 1 and 2: torch.Size([2, 4, 3])


In [ ]:
#Determinant
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
torch.det(h)

tensor(89.0000)

In [ ]:
#inverse of a matrix
torch.inverse(h)

tensor([[-0.0112,  0.1348, -0.2360],
        [-0.0899,  0.0787,  0.1124],
        [ 0.3596, -0.3146,  0.5506]])

### Comparision Operations

In [ ]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)

print(i)
print(j)

tensor([[0, 0, 7],
        [6, 6, 6]])
tensor([[7, 9, 4],
        [5, 8, 4]])


In [ ]:
#Greater than
i>j
#less than
i<j

# equal to
i==j

#not equal to
i != j



tensor([[True, True, True],
        [True, True, True]])

### 6.Special Functions

In [ ]:
k=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[5., 7., 0.],
        [6., 8., 4.]])

In [ ]:
#log
torch.log(k)

tensor([[2.0794, 2.1972, 0.6931],
        [0.6931, 0.0000, 1.3863]])

In [ ]:
#exp
torch.exp(k)

tensor([[2.9810e+03, 8.1031e+03, 7.3891e+00],
        [7.3891e+00, 2.7183e+00, 5.4598e+01]])

In [ ]:
#sqrt
torch.sqrt(k)

tensor([[2.8284, 3.0000, 1.4142],
        [1.4142, 1.0000, 2.0000]])

In [ ]:
#torch.sigmoid
torch.sigmoid(k)

tensor([[0.9997, 0.9999, 0.8808],
        [0.8808, 0.7311, 0.9820]])

In [ ]:
#softmax
torch.softmax(k,dim=0)

tensor([[0.2689, 0.2689, 0.0180],
        [0.7311, 0.7311, 0.9820]])

In [ ]:
#relu
torch.relu(k)

tensor([[5., 7., 0.],
        [6., 8., 4.]])

### Inplace Operations

In [ ]:
m=torch.rand(2,3)
n=torch.rand(2,3)
print(m)
print(n)

tensor([[0.9416, 0.6871, 0.7707],
        [0.3859, 0.4105, 0.2542]])
tensor([[0.6591, 0.8042, 0.7741],
        [0.9837, 0.8490, 0.8445]])


In [ ]:
m.add_(n)

tensor([[1.6008, 1.4913, 1.5448],
        [1.3695, 1.2596, 1.0987]])

In [ ]:
m

tensor([[1.6008, 1.4913, 1.5448],
        [1.3695, 1.2596, 1.0987]])

In [ ]:
n

tensor([[0.6591, 0.8042, 0.7741],
        [0.9837, 0.8490, 0.8445]])

In [ ]:
torch.relu(m)

tensor([[1.6008, 1.4913, 1.5448],
        [1.3695, 1.2596, 1.0987]])

In [ ]:
m.relu_()   #here _ is a implace operator

tensor([[1.6008, 1.4913, 1.5448],
        [1.3695, 1.2596, 1.0987]])

### Copying Tensor

In [ ]:
a=torch.rand(2,3)
a

tensor([[0.4127, 0.4009, 0.9368],
        [0.0409, 0.4389, 0.1147]])

In [ ]:
b=a

In [ ]:
b

tensor([[0.4127, 0.4009, 0.9368],
        [0.0409, 0.4389, 0.1147]])

In [ ]:
id(a)#memory location

132846765424576

In [ ]:
id(b)# referenced to same memory location of a

132846765424576

In [ ]:
# To create a new copy use clone function
b=a.clone()

In [ ]:
a

tensor([[0.4127, 0.4009, 0.9368],
        [0.0409, 0.4389, 0.1147]])

In [ ]:
b

tensor([[0.4127, 0.4009, 0.9368],
        [0.0409, 0.4389, 0.1147]])

In [ ]:
id(a )

132846765424576

In [ ]:
id(b)

132846769002032

In [ ]:
#now there is the different memory location for both a and b

### Tensor Operations on GPU

In [ ]:
torch.cuda.is_available()

False